# base-image/Dockerfile

FROM public.ecr.aws/lambda/python:3.12

# base-image/Dockerfile (New)
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu && \
    pip install transformers --no-cache-dir

